name: Build FFmpeg
on: workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        cfg:
          - target-os: win
            arch: x64
            extra-deps: mingw-w64
          - target-os: win
            arch: x86
            extra-deps: mingw-w64
          - target-os: linux
            arch: x64
            extra-deps: libva-dev libvdpau-dev
          - target-os: linux
            arch: aarch64
            extra-deps: gcc-aarch64-linux-gnu

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install -y nasm ${{ matrix.cfg.extra-deps }}

      - name: Build
        run: osu.Framework.NativeLibs/scripts/ffmpeg/build-${{ matrix.cfg.target-os }}.sh
        env:
          arch: ${{ matrix.cfg.arch }}

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.cfg.target-os }}-${{ matrix.cfg.arch }}
          path: ${{ matrix.cfg.target-os }}-${{ matrix.cfg.arch }}

  build-macos:
    name: Build macOS
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ilammy/setup-nasm@v1

      - name: Build
        run: osu.Framework.NativeLibs/scripts/ffmpeg/build-macOS.sh
        env:
          arch: ${{ matrix.arch }}

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: macOS-${{ matrix.arch }}
          path: macOS-${{ matrix.arch }}

  combine-macos:
    name: Combine macOS libs
    runs-on: macos-12
    needs: build-macos
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: macOS-x86_64
          path: macOS-x86_64
      - uses: actions/download-artifact@v3
        with:
          name: macOS-arm64
          path: macOS-arm64

      - name: Combine
        run: osu.Framework.NativeLibs/scripts/ffmpeg/combine_dylibs.sh

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: macOS-universal
          path: macOS-universal

  # The win-arm64 build runs in a special MinGW container to cross-compile successfully.
  build-win-arm64:
    name: Build Windows (arm64)
    runs-on: ubuntu-22.04
    container:
      image: mstorsjo/llvm-mingw:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: osu.Framework.NativeLibs/scripts/ffmpeg/build-win.sh
        env:
          arch: arm64

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: win-arm64
          path: win-arm64

  make-pr:
    name: Create pull request
    runs-on: ubuntu-22.04
    needs:
      - combine-macos
      - build
      - build-win-arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: macOS-universal
          path: osu.Framework.NativeLibs/runtimes/osx/native
      - uses: actions/download-artifact@v3
        with:
          name: linux-x64
          path: osu.Framework.NativeLibs/runtimes/linux-x64/native
      - uses: actions/download-artifact@v3
        with:
          name: win-arm64
          path: osu.Framework.NativeLibs/runtimes/win-arm64/native
      - uses: actions/download-artifact@v3
        with:
          name: win-x64
          path: osu.Framework.NativeLibs/runtimes/win-x64/native
      - uses: actions/download-artifact@v3
        with:
          name: win-x86
          path: osu.Framework.NativeLibs/runtimes/win-x86/native

      - uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update FFmpeg binaries
          title: Update FFmpeg binaries
          body: This PR has been auto-generated to update the FFmpeg binaries.
          branch: update-ffmpeg-binaries
          delete-branch: true
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
